In [148]:
import pandas as pd

In [149]:
movies=pd.read_csv('dataset.csv', sep=",", encoding='cp1252')

In [150]:
movies.head(10)

,id,title,city,desc,class
0,650158346685a6924136861b,Aga Khan Palace,Pune,Built in 1892 by Sultan Muhammed Shah Aga Khan...,"Palace,Fort"
1,650158346685a6924136861c,Chhatrapati Shivaji Maharaj Vastu Sangrahalaya,Mumbai,"In 1904, some leading citizens of Bombay decid...",Library
2,650158346685a6924136861d,Sanjay Gandhi National Park,Mumbai,The Sanjay Gandhi National Park area has a lon...,"National Park, Zoo, Trek, Caves,Adventure"
3,650158346685a6924136861e,Elephanta Caves,Raigad,The authenticity of the property has been well...,"Caves, Trek"
4,650158346685a6924136861f,Raigad Fort,Raigad,The Raigad Fort (earlier called as the Fort of...,"Fort, Trek, Historical, Caves"
5,650158346685a69241368620,Devagiri Daulatabad Fort,Aurangabad,Quite rightly referred to as one of the ‘Seven...,"Fort, Trek, Adventurous"
6,650158346685a69241368621,Veermata Jijabai Bhosale Udyan And Zoo,Mumbai,Rani Bagh is a fascinating subplot in the hist...,"Zoo, National Park"
7,650158346685a69241368622,Dadasaheb Phalke Chitranagari,Mumbai,The Mumbai Film City or Dadasaheb Phalke Chitr...,"Museum, FilmCity, Historical"
8,650158346685a69241368623,Ellora Caves,Aurangabad,The invaluable ensemble of 34 caves at Ellora ...,"Caves, Historical Site, Monument"
9,650158346685a69241368624,Shaniwar Wada,Pune,The foundation stone of the Shaniwar Wada was ...,"Palace, Fort, Arcitectural Site"

In [151]:
movies.describe()

,id,title,city,desc,class
count,12,12,12,12,12
unique,12,12,5,12,12
top,650158346685a6924136861b,Aga Khan Palace,Mumbai,Built in 1892 by Sultan Muhammed Shah Aga Khan...,"Palace,Fort"
freq,1,1,4,1,1

In [152]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      12 non-null     object
 1   title   12 non-null     object
 2   city    12 non-null     object
 3   desc    12 non-null     object
 4   class   12 non-null     object
dtypes: object(5)
memory usage: 612.0+ bytes

In [153]:
movies.isnull().sum()

id       0
title    0
city     0
desc     0
class    0
dtype: int64

Feature Selection Part

In [154]:
movies.columns

Index(['id', 'title', 'city', 'desc', 'class'], dtype='object')

In [155]:
movies=movies[['id', 'title', 'city', 'desc', 'class']]

In [156]:
movies

,id,title,city,desc,class
0,650158346685a6924136861b,Aga Khan Palace,Pune,Built in 1892 by Sultan Muhammed Shah Aga Khan...,"Palace,Fort"
1,650158346685a6924136861c,Chhatrapati Shivaji Maharaj Vastu Sangrahalaya,Mumbai,"In 1904, some leading citizens of Bombay decid...",Library
2,650158346685a6924136861d,Sanjay Gandhi National Park,Mumbai,The Sanjay Gandhi National Park area has a lon...,"National Park, Zoo, Trek, Caves,Adventure"
3,650158346685a6924136861e,Elephanta Caves,Raigad,The authenticity of the property has been well...,"Caves, Trek"
4,650158346685a6924136861f,Raigad Fort,Raigad,The Raigad Fort (earlier called as the Fort of...,"Fort, Trek, Historical, Caves"
5,650158346685a69241368620,Devagiri Daulatabad Fort,Aurangabad,Quite rightly referred to as one of the ‘Seven...,"Fort, Trek, Adventurous"
6,650158346685a69241368621,Veermata Jijabai Bhosale Udyan And Zoo,Mumbai,Rani Bagh is a fascinating subplot in the hist...,"Zoo, National Park"
7,650158346685a69241368622,Dadasaheb Phalke Chitranagari,Mumbai,The Mumbai Film City or Dadasaheb Phalke Chitr...,"Museum, FilmCity, Historical"
8,650158346685a69241368623,Ellora Caves,Aurangabad,The invaluable ensemble of 34 caves at Ellora ...,"Caves, Historical Site, Monument"
9,650158346685a69241368624,Shaniwar Wada,Pune,The foundation stone of the Shaniwar Wada was ...,"Palace, Fort, Arcitectural Site"
10,650d72ff14a2f4eb24e28989,Chand Minar,Aurangabad,"The Chand Minar whose literal meaning is the ""...",Architecture Site
11,650d79e814a2f4eb24eeb2f3,New Palace,Kolhapur,In the late 19th century a number of buildings...,"Palace, Trek,Fort"

In [157]:
movies['tags'] = movies['desc']+movies['city']+movies['class']

In [158]:
movies

,id,title,city,desc,class,tags
0,650158346685a6924136861b,Aga Khan Palace,Pune,Built in 1892 by Sultan Muhammed Shah Aga Khan...,"Palace,Fort",Built in 1892 by Sultan Muhammed Shah Aga Khan...
1,650158346685a6924136861c,Chhatrapati Shivaji Maharaj Vastu Sangrahalaya,Mumbai,"In 1904, some leading citizens of Bombay decid...",Library,"In 1904, some leading citizens of Bombay decid..."
2,650158346685a6924136861d,Sanjay Gandhi National Park,Mumbai,The Sanjay Gandhi National Park area has a lon...,"National Park, Zoo, Trek, Caves,Adventure",The Sanjay Gandhi National Park area has a lon...
3,650158346685a6924136861e,Elephanta Caves,Raigad,The authenticity of the property has been well...,"Caves, Trek",The authenticity of the property has been well...
4,650158346685a6924136861f,Raigad Fort,Raigad,The Raigad Fort (earlier called as the Fort of...,"Fort, Trek, Historical, Caves",The Raigad Fort (earlier called as the Fort of...
5,650158346685a69241368620,Devagiri Daulatabad Fort,Aurangabad,Quite rightly referred to as one of the ‘Seven...,"Fort, Trek, Adventurous",Quite rightly referred to as one of the ‘Seven...
6,650158346685a69241368621,Veermata Jijabai Bhosale Udyan And Zoo,Mumbai,Rani Bagh is a fascinating subplot in the hist...,"Zoo, National Park",Rani Bagh is a fascinating subplot in the hist...
7,650158346685a69241368622,Dadasaheb Phalke Chitranagari,Mumbai,The Mumbai Film City or Dadasaheb Phalke Chitr...,"Museum, FilmCity, Historical",The Mumbai Film City or Dadasaheb Phalke Chitr...
8,650158346685a69241368623,Ellora Caves,Aurangabad,The invaluable ensemble of 34 caves at Ellora ...,"Caves, Historical Site, Monument",The invaluable ensemble of 34 caves at Ellora ...
9,650158346685a69241368624,Shaniwar Wada,Pune,The foundation stone of the Shaniwar Wada was ...,"Palace, Fort, Arcitectural Site",The foundation stone of the Shaniwar Wada was ...
10,650d72ff14a2f4eb24e28989,Chand Minar,Aurangabad,"The Chand Minar whose literal meaning is the ""...",Architecture Site,"The Chand Minar whose literal meaning is the ""..."
11,650d79e814a2f4eb24eeb2f3,New Palace,Kolhapur,In the late 19th century a number of buildings...,"Palace, Trek,Fort",In the late 19th century a number of buildings...

In [159]:
new_data  = movies.drop(columns=['desc', 'city', 'class'])

In [160]:
new_data

,id,title,tags
0,650158346685a6924136861b,Aga Khan Palace,Built in 1892 by Sultan Muhammed Shah Aga Khan...
1,650158346685a6924136861c,Chhatrapati Shivaji Maharaj Vastu Sangrahalaya,"In 1904, some leading citizens of Bombay decid..."
2,650158346685a6924136861d,Sanjay Gandhi National Park,The Sanjay Gandhi National Park area has a lon...
3,650158346685a6924136861e,Elephanta Caves,The authenticity of the property has been well...
4,650158346685a6924136861f,Raigad Fort,The Raigad Fort (earlier called as the Fort of...
5,650158346685a69241368620,Devagiri Daulatabad Fort,Quite rightly referred to as one of the ‘Seven...
6,650158346685a69241368621,Veermata Jijabai Bhosale Udyan And Zoo,Rani Bagh is a fascinating subplot in the hist...
7,650158346685a69241368622,Dadasaheb Phalke Chitranagari,The Mumbai Film City or Dadasaheb Phalke Chitr...
8,650158346685a69241368623,Ellora Caves,The invaluable ensemble of 34 caves at Ellora ...
9,650158346685a69241368624,Shaniwar Wada,The foundation stone of the Shaniwar Wada was ...
10,650d72ff14a2f4eb24e28989,Chand Minar,"The Chand Minar whose literal meaning is the ""..."
11,650d79e814a2f4eb24eeb2f3,New Palace,In the late 19th century a number of buildings...

In [161]:
from sklearn.feature_extraction.text import CountVectorizer

In [162]:
cv=CountVectorizer(max_features=10000, stop_words='english')

In [163]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [164]:
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [165]:
vector.shape

(12, 890)

In [166]:
from sklearn.metrics.pairwise import cosine_similarity

In [167]:
similarity=cosine_similarity(vector)

In [168]:
similarity

array([[1.        , 0.08760058, 0.11399759, 0.01023825, 0.10167554,
        0.16396995, 0.07027284, 0.0557086 , 0.01292072, 0.1463127 ,
        0.03042903, 0.13760755],
       [0.08760058, 1.        , 0.03370361, 0.04035945, 0.07734884,
        0.05386448, 0.09811031, 0.07116821, 0.02688173, 0.05654593,
        0.03598561, 0.08218978],
       [0.11399759, 0.03370361, 1.        , 0.06302535, 0.03294218,
        0.0180246 , 0.22530753, 0.03492856, 0.11267919, 0.03532086,
        0.01873172, 0.01283476],
       [0.01023825, 0.04035945, 0.06302535, 1.        , 0.02465478,
        0.05396033, 0.0161881 , 0.        , 0.23414542, 0.0475831 ,
        0.08411582, 0.05763521],
       [0.10167554, 0.07734884, 0.03294218, 0.02465478, 1.        ,
        0.1861468 , 0.03384487, 0.01788695, 0.0497831 , 0.14507967,
        0.18465627, 0.12049942],
       [0.16396995, 0.05386448, 0.0180246 , 0.05396033, 0.1861468 ,
        1.        , 0.01851852, 0.06524669, 0.04993865, 0.06350529,
        0.10905505, 0.11867817],
       [0.07027284, 0.09811031, 0.22530753, 0.0161881 , 0.03384487,
        0.01851852, 1.        , 0.07829603, 0.06128834, 0.01360828,
        0.03849002, 0.        ],
       [0.0557086 , 0.07116821, 0.03492856, 0.        , 0.01788695,
        0.06524669, 0.07829603, 1.        , 0.03359043, 0.02397317,
        0.03390318, 0.02787609],
       [0.01292072, 0.02688173, 0.11267919, 0.23414542, 0.0497831 ,
        0.04993865, 0.06128834, 0.03359043, 1.        , 0.03002503,
        0.0212309 , 0.03394341],
       [0.1463127 , 0.05654593, 0.03532086, 0.0475831 , 0.14507967,
        0.06350529, 0.01360828, 0.02397317, 0.03002503, 1.        ,
        0.08956686, 0.15504051],
       [0.03042903, 0.03598561, 0.01873172, 0.08411582, 0.18465627,
        0.10905505, 0.03849002, 0.03390318, 0.0212309 , 0.08956686,
        1.        , 0.08907453],
       [0.13760755, 0.08218978, 0.01283476, 0.05763521, 0.12049942,
        0.11867817, 0.        , 0.02787609, 0.03394341, 0.15504051,
        0.08907453, 1.        ]])

In [169]:
new_data[new_data['title']=="Elephanta Caves"].index[0]

3

In [170]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:4]:
    print(new_data.iloc[i[0]].title)

Sanjay Gandhi National Park
Veermata Jijabai Bhosale Udyan And Zoo
Aga Khan Palace
Ellora Caves

In [171]:
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].id)

In [172]:
recommand("Raigad Fort")

650158346685a6924136861f
650158346685a69241368620
650d72ff14a2f4eb24e28989
650158346685a69241368624
650d79e814a2f4eb24eeb2f3

In [173]:
import pickle

In [174]:
pickle.dump(new_data, open('recommender.pkl', 'wb'))

In [175]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [176]:
pickle.load(open('recommender.pkl', 'rb'))

,id,title,tags
0,650158346685a6924136861b,Aga Khan Palace,Built in 1892 by Sultan Muhammed Shah Aga Khan...
1,650158346685a6924136861c,Chhatrapati Shivaji Maharaj Vastu Sangrahalaya,"In 1904, some leading citizens of Bombay decid..."
2,650158346685a6924136861d,Sanjay Gandhi National Park,The Sanjay Gandhi National Park area has a lon...
3,650158346685a6924136861e,Elephanta Caves,The authenticity of the property has been well...
4,650158346685a6924136861f,Raigad Fort,The Raigad Fort (earlier called as the Fort of...
5,650158346685a69241368620,Devagiri Daulatabad Fort,Quite rightly referred to as one of the ‘Seven...
6,650158346685a69241368621,Veermata Jijabai Bhosale Udyan And Zoo,Rani Bagh is a fascinating subplot in the hist...
7,650158346685a69241368622,Dadasaheb Phalke Chitranagari,The Mumbai Film City or Dadasaheb Phalke Chitr...
8,650158346685a69241368623,Ellora Caves,The invaluable ensemble of 34 caves at Ellora ...
9,650158346685a69241368624,Shaniwar Wada,The foundation stone of the Shaniwar Wada was ...
10,650d72ff14a2f4eb24e28989,Chand Minar,"The Chand Minar whose literal meaning is the ""..."
11,650d79e814a2f4eb24eeb2f3,New Palace,In the late 19th century a number of buildings...